import 'package:flutter/material.dart';

class PlayingCardWidget extends StatelessWidget {
  final String rank;
    final String suitSymbol;
      final bool isRed;
        final double width;
          final bool highlight;

            const PlayingCardWidget({super.key, required this.rank, required this.suitSymbol, this.isRed = false, this.width = 62, this.highlight = false});

              @override
                Widget build(BuildContext context) {
                    final color = isRed ? const Color(0xFFC8102E) : const Color(0xFF161616);
                        final radius = width * 0.11;
                            return Container(
                                  width: width,
                                        height: width * 1.42,
                                              decoration: BoxDecoration(
                                                      borderRadius: BorderRadius.circular(radius),
                                                              gradient: const LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [Colors.white, Color(0xFFF6F4EF)]),
                                                                      border: Border.all(color: highlight ? const Color(0xFFFFD700) : const Color(0xFFD8D5CE), width: highlight ? 2.2 : 0.8),
                                                                              boxShadow: highlight
                                                                                          ? [
                                                                                                          BoxShadow(color: const Color(0xFFFFD700).withOpacity(0.55), blurRadius: 14, spreadRadius: 1, offset: const Offset(0, 0)),
                                                                                                                          BoxShadow(color: Colors.black.withOpacity(0.28), blurRadius: 8, offset: const Offset(1, 3)),
                                                                                                                                        ]
                                                                                                                                                    : [
                                                                                                                                                                    BoxShadow(color: Colors.black.withOpacity(0.22), blurRadius: 6, offset: const Offset(1, 2)),
                                                                                                                                                                                    BoxShadow(color: Colors.black.withOpacity(0.10), blurRadius: 1, offset: const Offset(0, 1)),
                                                                                                                                                                                                  ],
                                                                                                                                                                                                        ),
                                                                                                                                                                                                              child: Padding(
                                                                                                                                                                                                                      padding: EdgeInsets.all(width * 0.045),
                                                                                                                                                                                                                              child: Container(
                                                                                                                                                                                                                                        decoration: BoxDecoration(
                                                                                                                                                                                                                                                    borderRadius: BorderRadius.circular(radius * 0.7),
                                                                                                                                                                                                                                                                border: Border.all(color: color.withOpacity(0.08), width: 1),
                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                    child: Padding(
                                                                                                                                                                                                                                                                                                padding: EdgeInsets.all(width * 0.055),
                                                                                                                                                                                                                                                                                                            child: Stack(children: [
                                                                                                                                                                                                                                                                                                                          _corner(color, false),
                                                                                                                                                                                                                                                                                                                                        Center(
                                                                                                                                                                                                                                                                                                                                                        child: Text(
                                                                                                                                                                                                                                                                                                                                                                          suitSymbol,
                                                                                                                                                                                                                                                                                                                                                                                            style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: width * 0.44,
                                                                                                                                                                                                                                                                                                                                                                                                                                    color: color.withOpacity(0.92),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        shadows: [Shadow(color: Colors.black.withOpacity(0.15), blurRadius: 2, offset: const Offset(0.5, 1))],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Positioned(bottom: 0, right: 0, child: Transform.rotate(angle: 3.14159, child: _corner(color, true))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Widget _corner(Color color, bool isBottom) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text(rank, style: TextStyle(fontSize: width * 0.20, fontWeight: FontWeight.w800, color: color, height: 1.0, letterSpacing: -0.3)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  SizedBox(height: width * 0.01),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text(suitSymbol, style: TextStyle(fontSize: width * 0.155, color: color, height: 1.0)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              class CardBackWidget extends StatelessWidget {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                final double width;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const CardBackWidget({super.key, this.width = 62});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          final radius = width * 0.11;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: width,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height: width * 1.42,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: BorderRadius.circular(radius),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gradient: const LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [Color(0xFF9A0000), Color(0xFF4A0000)]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: Border.all(color: const Color(0xFFE8C97A), width: 1.3),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          BoxShadow(color: Colors.black.withOpacity(0.30), blurRadius: 6, offset: const Offset(1, 3)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BoxShadow(color: Colors.black.withOpacity(0.12), blurRadius: 1, offset: const Offset(0, 1)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: EdgeInsets.all(width * 0.09),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: BorderRadius.circular(radius * 0.6),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: Border.all(color: const Color(0xFFE8C97A).withOpacity(0.55), width: 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: Center(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: width * 0.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      height: width * 0.85,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: BorderRadius.circular(width * 0.05),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: Border.all(color: const Color(0xFFE8C97A).withOpacity(0.45), width: 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gradient: LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [const Color(0xFFE8C97A).withOpacity(0.12), Colors.transparent]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }